// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCrwhO8iDlKWxsODf46ZdgYbB_gtIOdhk',
    appId: '1:247585563752:web:5de9598395fdff8dc047dd',
    messagingSenderId: '247585563752',
    projectId: 'staymate-a3382',
    authDomain: 'staymate-a3382.firebaseapp.com',
    storageBucket: 'staymate-a3382.firebasestorage.app',
    measurementId: 'G-6JD1CL4JT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLBmQbo7icK2u6Lt4eQmK8AMxgc2hCXtg',
    appId: '1:247585563752:android:846b4c474b7408bbc047dd',
    messagingSenderId: '247585563752',
    projectId: 'staymate-a3382',
    storageBucket: 'staymate-a3382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVkcrLB7Aq1sEasolLgXR2uFUj_tN-Uqw',
    appId: '1:247585563752:ios:7742f4d4be8082cec047dd',
    messagingSenderId: '247585563752',
    projectId: 'staymate-a3382',
    storageBucket: 'staymate-a3382.firebasestorage.app',
    iosClientId: '247585563752-eoekv1rndse43q3i1vqn4ajbjmavi37c.apps.googleusercontent.com',
    iosBundleId: 'com.example.staymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVkcrLB7Aq1sEasolLgXR2uFUj_tN-Uqw',
    appId: '1:247585563752:ios:7742f4d4be8082cec047dd',
    messagingSenderId: '247585563752',
    projectId: 'staymate-a3382',
    storageBucket: 'staymate-a3382.firebasestorage.app',
    iosClientId: '247585563752-eoekv1rndse43q3i1vqn4ajbjmavi37c.apps.googleusercontent.com',
    iosBundleId: 'com.example.staymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCrwhO8iDlKWxsODf46ZdgYbB_gtIOdhk',
    appId: '1:247585563752:web:e7807d6ed03e2035c047dd',
    messagingSenderId: '247585563752',
    projectId: 'staymate-a3382',
    authDomain: 'staymate-a3382.firebaseapp.com',
    storageBucket: 'staymate-a3382.firebasestorage.app',
    measurementId: 'G-B0DSJ1RGT3',
  );
}
